Repository North-Seattle-College/ad440-winter2021-tuesday-repo, pull requests merged in 2021-03, with the labels that each got.

#217 UI create user
  ui/src/App.js
  ui/src/components/css/CreateUserScreen.css
  ui/src/components/navigation/NavLinks.js
  ui/src/components/pages/CreateUserScreen.js
Labels: task, team4

#243 update create user UI
  ui/src/components/pages/CreateUserScreen.js
Labels: task, team4

#240 Converted Connections to Live
  package-lock.json
  package.json
  ui/src/components/css/Button.css
  ui/src/components/css/TaskListScreen.css
  ui/src/components/css/UserListScreen.css
  ui/src/components/data/dummy-tasks.json
  ui/src/components/data/dummy-tests.json
  ui/src/components/data/dummy-users.json
  ui/src/components/data/report_for_30req.json
  ui/src/components/pages/ArtilleryDetailScreen.js
  ui/src/components/pages/ArtilleryListScreen.js
  ui/src/components/pages/ServerlessDetailScreen.js
  ui/src/components/pages/ServerlessListScreen.js
  ui/src/components/pages/TaskDetailScreen.js
  ui/src/components/pages/TaskListScreen.js
  ui/src/components/pages/UserDetailScreen.js
  ui/src/components/pages/UserListScreen.js
Labels: bug, team1

#237 [T1T6] Redis automation
  automation/redis_cache/deploy.ps1
  automation/redis_cache/template.json
Labels: team1

#247 Derek task1 sprint4: Sequential Tests and Naming Conventions
  .github/workflows/artillery-users-id-tasks-id.yml
  .github/workflows/artillery-users-id-tasks.yml
  .github/workflows/artillery-users-id.yml
  .github/workflows/artillery-users.yaml
  .github/workflows/deploy-azure-function.yml
  .github/workflows/deploy-ui.yml
  .github/workflows/serverless-artillery-github-actions.yml
  .github/workflows/serverless-artillery-users-id-tasks-id.yml
  .github/workflows/serverless-artillery-users-id-tasks.yml
  .github/workflows/serverless-artillery-users-id.yml
  .github/workflows/serverless-artillery-users.yml
  testing/artillery/artillery-users-id-tasks-id.yml
  testing/artillery/artillery-users-id-tasks.yml
  testing/artillery/artillery-users-id.yml
  testing/artillery/artillery-users.yaml
  testing/serverless-artillery/serverless-artillery-users-id-tasks-id.yml
  testing/serverless-artillery/serverless-artillery-users-id-tasks.yml
  testing/serverless-artillery/serverless-artillery-users-id.yml
  testing/serverless-artillery/serverless-artillery-users.yml
Labels: task, team3

#245 update UI create user
  ui/src/components/pages/CreateUserScreen.js
Labels: task, team4

#252 headless chrome ui test for userId/tasks endpoint
  .github/workflows/headlessUITest_Tasks.yml
  README.md
  testing/headless-chrome/package-lock.json
  testing/headless-chrome/package.json
Labels: task, team1

#250 Screenshot task-id endpoint
  .github/workflows/screenshot-taskid.yml
Labels: task, team1

#253 Write action for UI tests for /users
  .github/workflows/browser-test-ui-users.yml
  ui/src/components/pages/UserListScreen.js
Labels: task, team1

#256 Initial create task page UI
  ui/src/App.js
  ui/src/components/css/CreateTaskScreen.css
  ui/src/components/navigation/NavLinks.js
  ui/src/components/pages/CreateTaskScreen.js
Labels: task, team4

#257 api tasks method fix
  functions/HttpTriggerUserIdTask/__init__.py
  functions/HttpTriggerUsers/__init__.py
Labels: bug

#261 fix response code
  ui/src/components/pages/CreateUserScreen.js
Labels: task, team4

#262 [TASK 1, SPRINT 4] Fix the response codes for wrong input for POST /users
  .vscode/settings.json
  functions/HttpTriggerUsers/__init__.py
Labels: task, team2

#258 Vita/issues/215 deploy react for browsing artillery results
  ui/package-lock.json
  ui/src/components/pages/ArtilleryListScreen.js
Labels: bug, team1

#249 added .yml file for screenshot-user-userid action
  .github/workflows/screenshot-user-userid.yml
Labels: task, team1

#267 api path fix
  ui/src/components/pages/CreateTaskScreen.js
Labels: task, team4

#264 Shopping List of Changes
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  example/deploy-AppGateway.ps1
  example/template.json
  functions/.vscode/extensions.json
  functions/.vscode/launch.json
  functions/.vscode/settings.json
  functions/.vscode/tasks.json
  ui/src/components/css/HomeScreen.css
  ui/src/components/css/TaskDetailScreen.css
  ui/src/components/css/TaskListScreen.css
  ui/src/components/css/TestDetailScreen.css
  ui/src/components/css/TestListScreen.css
  ui/src/components/css/UserDetailScreen.css
  ui/src/components/css/UserListScreen.css
  ui/src/components/pages/ArtilleryDetailScreen.js
  ui/src/components/pages/ArtilleryListScreen.js
  ui/src/components/pages/CreateTaskScreen.js
  ui/src/components/pages/CreateUserScreen.js
  ui/src/components/pages/HomeScreen.js
  ui/src/components/pages/ServerlessDetailScreen.js
  ui/src/components/pages/ServerlessListScreen.js
  ui/src/components/pages/TaskDetailScreen.js
  ui/src/components/pages/TaskListScreen.js
  ui/src/components/pages/UserDetailScreen.js
  ui/src/components/pages/UserListScreen.js
Labels: bug, team1

#271 fixed bug in api/users/{userId}/tasks
  functions/HttpTriggerUserIdTask/__init__.py
Labels: bug

#272 fix bug with api/user/{userId}/tasks endpoint
  functions/HttpTriggerUserIdTask/__init__.py
Labels: bug

#275 Fixing Create Tasks / Listing Tasks
  ui/package-lock.json
  ui/src/App.js
  ui/src/components/navigation/NavLinks.js
  ui/src/components/pages/CreateTaskScreen.js
  ui/src/components/pages/TaskListScreen.js
Labels: bug

#277 Vita rox/issues/270/create automation script for key vault
  automation/key-vault/deploy.ps1
  automation/key-vault/template.json
Labels: task, team1

#246 Headless chrome test users/{user_Id/tasks}
  testing/ui-tests/ui-test-users-id-tasks.js
Labels: task, team3

#260 [Sprint4][Team3][Anthony]-Implement Headless Chrome Test for React UI for /users
  .github/workflows/serverless-artillery-users-id-tasks.yml
  testing/serverless-artillery/serverless-artillery-users-id-tasks.yml
  testing/ui-tests/ui-test-users.js
Labels: task, team3

#282 Joanna headless chrome test sprint4
  testing/ui-tests/ui-test-users-id-tasks-id.js
Labels: bug, team3

#287 Fix the response codes for wrong input for POST /users/{user_id}
  functions/HttpTriggerUserId/__init__.py
Labels: team2

#291 API endpoint fix
  functions/HttpTriggerRedisPrototype/__init__.py
  functions/HttpTriggerUserId/__init__.py
  functions/HttpTriggerUserIdTask/__init__.py
  functions/HttpTriggerUserIdTaskId/__init__.py
  functions/HttpTriggerUsers/__init__.py
  functions/Utils/RequestHandler.py
  functions/Utils/dbHandler.py
  functions/requirements.txt
Labels: bug, important

#292 Redis caching and some other things
  functions/HttpTriggerUserIdTaskId/__init__.py
  functions/HttpTriggerUsers/__init__.py
Labels: task, team1

#288 [Task 3 | Sprint 4] POST /users/{user_id}/tasks with swagger documentation
  .github/workflows/sql-injection-test.yml
  Swagger/swagger-users-userid-task.yaml
  automation/functions/create_azure_storageacct_with_containers.ps1
  automation/functions/createstorageaccount.ps1
  automation/functions/templatestorage.json
  functions/HttpTriggerUserId/function.json
  functions/HttpTriggerUserIdTask/function.json
  package-lock.json
  package.json
Labels: task, team2

#302 React UI for deleting tasks
  ui/package-lock.json
  ui/package.json
  ui/src/components/pages/TaskDetailScreen.js
  ui/src/components/pages/TaskListScreen.js
Labels: task, team2

#305 sql injections github actions
  .github/workflows/sql-injections-idTask.yml
Labels: task, team4

#308 Updatde sql-injections-idTask.yml
  .github/workflows/sql-injections-idTask.yml
Labels: task, team4

#312 Fixed Delete Button
  ui/src/components/pages/TaskDetailScreen.js
  ui/src/components/pages/TaskListScreen.js
Labels: bug

#310 SQL-injections-idTask.yml
  .github/workflows/sql-injections-idTask.yml
Labels: task, team4

#307 [Sprint5][Team3][Task5] - fix the routing for /users/{user_id}/tasks/{task_id} in React
  .gitignore
  ui/src/App.js
Labels: bug, task, team3

#314 Update sql-injections-idTask.yml
  .github/workflows/sql-injections-idTask.yml
Labels: task, team4

#315 sql-injection-userId
  .github/workflows/sql-injections-userID.yml
Labels: task, team4

#316 [Task 1][Sprint 5]Convert the SQL injection test into GitHub Action
  .github/workflows/sql-injection-test.yml
  Swagger/swagger-users-userid-task.yaml
Labels: task, team2

#323 SQL injection test
  .github/workflows/sql-injections-userID.yml
Labels: task, team4

#331 Redis cache users pn
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  functions/.vscode/extensions.json
  functions/.vscode/launch.json
  functions/.vscode/settings.json
  functions/.vscode/tasks.json
  functions/HttpTriggerUsers/__init__.py
  functions/local.settings.json
  functions/requirements.txt
  package-lock.json
  package.json
Labels: task, team4

#324 Write Sql-injection For Delete users
  .github/workflows/sql-injection-delete-user-userid.yml
  testing/sql-injection/delete-user-userId.json
Labels: task, team2

#319 adds caching for users/{user_id}/tasks
  functions/HttpTriggerUserIdTask/__init__.py
Labels: task, team1

#321 Caching for userId/tasks/taskId
  functions/HttpTriggerUserIdTaskId/__init__.py
Labels: task, team1

#345 Auto azure function deploy pn
  .github/workflows/deploy-azure-function.yml
Labels: task, team4

#325 Convert the SQL Injection test into GitHub Action
  .github/workflows/sql-injection-user.yml
Labels: task, team2

#353 Fix bug in headless chrome
  testing/ui-tests/ui-test-users-id-tasks-id.js
  testing/ui-tests/ui-test-users-id-tasks.js
  testing/ui-tests/ui-test-users-userid.js
  testing/ui-tests/ui-test-users.js
Labels: bug, team3

#347 Spn | Swagger for /users
  Swagger/users.yaml
Labels: task

#340 Swagger for /users/{userid}
  Swagger/userid.yaml
Labels: task, team2

#356 Created swagger file for users/{userid}/tasks
  swagger/useridtask.yaml
Labels: task, team2

#358 Auto azure function deploy pn
  automation/functions/azuredeploy.json
Labels: task, team4
