Repository North-Seattle-College/ad440-winter2021-tuesday-repo, pull requests merged in 2021-02, with the labels that each got.

#86 Git action to deploy function to azure
  .github/workflows/deploy-Az-function.yml
Labels: task, team4

#87 Delete deploy-Az-function.yml
  .github/workflows/deploy-Az-function.yml
Labels: task, team4

#94 Sprint 2] team 4] task 6 change the yaml for artillery on the vm to test the /users api with 100 req/sec for 15 mins
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  testing/artillery/report_for_30req.json
  testing/artillery/vm_url_performance.yml
  testing/artillery/vm_url_performance_30req.yml
Labels: task, team4

#95 Task4team4 sw
  .github/workflows/learn-github-actions.yml
  testing/Serverless-Artillery/testGithubactions.txt
Labels: task, team4

#97 Github Actions Serverless Artillery
  .github/workflows/serverless_art-github-actions.yml
  testing/Serverless-Artillery/script.yml
  testing/Serverless-Artillery/testGithubactions.txt
Labels: task, team4

#96 Github action deploy function to azure
  .github/workflows/deploy-Az-function.yml
Labels: task, team4

#98 run serverless artillery tests against the /users API when new YAML is checked into the development repository
  .github/workflows/serverless_art_github-actions.yml
  testing/Serverless-Artillery/users_api_script.yml
Labels: task, team4

#103 Team4 task5 pn
  .github/workflows/gha_artillery.yml
  action.yml
  dist1/index.js
  dist1/pagent.exe
  testing/artillery/githubaction_url_performance.yml
Labels: task, team4

#105 Team04 sprint02 task01
  package-lock.json
  testing/artillery/perftest.yaml
  testing/kubernetes-perf-test/.dockerignore
  testing/kubernetes-perf-test/Dockerfile
  testing/kubernetes-perf-test/azure-pipelines.yml
  testing/kubernetes-perf-test/container-scripts/run-load-test.ps1
  testing/kubernetes-perf-test/load.yaml
  testing/kubernetes-perf-test/perftest.py
Labels: task, team4

#107 Updating GitHub Action for Artillery Testing
  .github/workflows/gha_artillery.yml
  action.yml
  dist1/index.js
  dist1/pagent.exe
Labels: task, team4

#93 Derek task4 sprint2: Dynamic Automation of IP Address
  automation/ip-address-script/create-ip.ps1
  automation/ip-address-script/template.json
  automation/network-security-group/template/parameters.json
  automation/network-security-group/template/template.json
  automation/template/parameters.json
  automation/template/template.json
Labels: task, team3

#99 Featurebranch paul - Team 2 - Task 5 - Storage account - Use New-AzRespourceGroupDeployment with template.json and without parameters.json
  automation/functions/create_azure_resource.ps1
  example/myscript.py
Labels: task, team2

#62 [Sprint 1 - Task 6] - Implement script to create Application Gateway Account
  exmple/deploy-AppGateway.ps1
  exmple/template.json
Labels: task, team2

#100 updated template url
  automation/functions/script.ps1
Labels: important, team2

#85 [Sprint 2][Team 1][Task 2] Implement logging for /users/{user_id}
  .gitignore
  functions/CreateUserId/__init__.py
  functions/DeleteUserId/__init__.py
  functions/GetUserId/__init__.py
Labels: task, team1

#81 Create Virtual Network PS Script using template.json
  automation/vnet/deploy-vnet.ps1
  automation/vnet/template.json
Labels: task, team3

#91 Vita/issues/50/display tasks by user
  package-lock.json
  ui/public/favicon.ico
  ui/src/components/css/App.css
  ui/src/components/css/HomeScreen.css
  ui/src/components/css/NavScreen.css
  ui/src/components/data/dummy-tasks.json
  ui/src/components/navigation/NavScreen.js
  ui/src/components/pages/HomeScreen.js
  ui/src/components/pages/TaskDetailsScreen.js
  ui/src/components/pages/TasksScreen.js
Labels: task, team1

#117 Completed azure api functions
  functions/CreateUserId/__init__.py
  functions/DeleteUserId/__init__.py
  functions/GetTasks/__init__.py
  functions/GetTasks/function.json
  functions/GetUserId/__init__.py
  functions/GetUserId/function.json
  functions/HttpTriggerDeleteTask/__init__.py
  functions/HttpTriggerDeleteTask/sample.dat
  functions/HttpTriggerGetTask/__init__.py
  functions/HttpTriggerGetTask/function.json
  functions/HttpTriggerGetTask/sample.dat
  functions/HttpTriggerPutTask/__init__.py
  functions/HttpTriggerPutTask/sample.dat
  functions/HttpTriggerUserId/__init__.py
  functions/HttpTriggerUserId/function.json
  functions/HttpTriggerUserId/sample.dat
  functions/HttpTriggerUserIdTask/__init__.py
  functions/HttpTriggerUserIdTask/function.json
  functions/HttpTriggerUserIdTask/sample.dat
  functions/HttpTriggerUserIdTaskId/__init__.py
  functions/HttpTriggerUserIdTaskId/function.json
  functions/HttpTriggerUserIdTaskId/sample.dat
  functions/HttpTriggerUsers/__init__.py
  functions/HttpTriggerUsers/function.json
  functions/HttpTriggerUsers/sample.dat
  functions/Model/Task.py
  functions/Model/User.py
  functions/Utils/dbHandler.py
Labels: bug, task, team1

#92 Feature automation sql resources
  automation/sql-server/sql-resource.ps1
  automation/sql-server/template.json
Labels: task, team3

#106 [Sprint 2][Team 2][Task 2] Use New-AzRespourceGroupDeployment with template.json and without parameters.json
  automation/functions/deploy-template.ps1
Labels: task, team2

#102 [Task 4] Function /users/{user_id}/tasks/{task_id} - Use New-AzResourceGroupDeployment with template.json and without parameters.json
  .gitignore
  automation/function-automation/Task4Script/azuredeploy.json
  automation/function-automation/Task4Script/deployfunctionScript.ps1
  automation/function-automation/Task4Script/template.json
Labels: task, team2

#130 adds ui update upload automation via github actions
  .github/workflows/ui-update-automation.yml
Labels: team4

#136 Rename UI Deployment Action for Naming Convention
  deploy-ui.yml
Labels: task, team4

#139 Renames UI Github Action for new naming convention
  .github/workflows/deploy-ui.yml
Labels: task, team4

#141 Github actions to run serverless artillery testsTask4 Team4 sw
  .github/workflows/serverless_art_github-actions.yml
  testing/Serverless-Artillery/users_api_script.yml
Labels: task, team4

#124 pk sprint3 task2 - Implement React view for /users/{user_id}/tasks/{task_id}
  functions/requirements.txt
  ui/src/App.js
  ui/src/components/data/dummy-tests.json
  ui/src/components/pages/TaskListScreen.js
  ui/src/components/pages/TasksScreen.js
Labels: task, team1

#125 Joanna VM automation sprint2
  automation/vm/deploy-vm.ps1
  automation/vm/parameters.json
  automation/vm/template.json
Labels: task, team3

#148 Task2 team4 upload perf artillery test to azure blob storage
  .github/workflows/artillery-perf-test-user-url-report-upload-to-azure-blob-store.yaml
Labels: task, team4

#149 testion uploading artillery perf test to Azure Storage
  .github/workflows/artillery-perf-test-user-url-report-upload-to-azure-blob-store.yaml
Labels: task, team4

#151 Task2 team4 upload perf artillery test to azure blob storage
  .github/workflows/artillery-perf-test-user-url-report-upload-to-azure-blob-storage.yaml
  .github/workflows/artillery-perf-test-user-url-report-upload-to-azure-blob-store.yaml
  testing/artillery/artillery-perf-test-user-api.yaml
Labels: task, team4

#152 Task2 team4 upload perf artillery test to azure blob storage
  .github/workflows/artillery-perf-test-user-url-report-upload-to-azure-blob-storage.yaml
Labels: task, team4

#153 Task2 team4 upload perf artillery test to azure blob storage
  .github/workflows/artillery-perf-test-user-url-report-upload-to-azure-blob-storage.yaml
Labels: task, team4

#154 Task2 Team4 - Upload test report to Azure Storage
  .github/workflows/artillery-perf-test-user-url-report-upload-to-azure-blob-storage.yaml
Labels: task, team4

#121 added the clear az context for authentication bug
  automation/network-security-group/create-nsg-v2.ps1
Labels: bug, team3

#157 Team1-Task3-Sprint3
  ui/src/components/css/TestDetailScreen.css
  ui/src/components/css/UsersScreen.css
  ui/src/components/pages/ArtilleryDetailScreen.js
  ui/src/components/pages/UsersScreen.js
Labels: task, team1

#162 Sprint3 task6 amb
  ui/src/components/css/TestListScreen.css
  ui/src/components/css/UserListScreen.css
  ui/src/components/css/UserScreen.css
  ui/src/components/pages/ServerlessListScreen.js
  ui/src/components/pages/UserListScreen.js
  ui/src/components/pages/UserScreen.js
Labels: task, team1

#165 Implement react users/usersid page
  ui/src/components/css/UserListScreen.css
  ui/src/components/pages/UserListScreen.js
Labels: task, team1

#166 UI Patch
  ui/src/App.js
  ui/src/components/css/TaskDetailScreen.css
  ui/src/components/css/TaskListScreen.css
  ui/src/components/css/UserDetailScreen.css
  ui/src/components/navigation/NavLinks.js
  ui/src/components/pages/TaskDetailScreen.js
  ui/src/components/pages/TasksScreen.js
  ui/src/components/pages/UserDetailScreen.js
  ui/src/components/pages/UserListScreen.js
Labels: bug

#167 Fix CSS + Dummy Data
  ui/src/components/css/NavScreen.css
  ui/src/components/data/dummy-tests.json
  ui/src/components/data/dummy-users.json
Labels: bug

#164 Jen artillery test for " /users/{user_id}/tasks" - 10 concurrent requests per second for 5 min
  .github/workflows/artillery-action-users-id-tasks-api.yml
  testing/artillery/artillery-test-users-id-tasks-api.yml
Labels: task, team3

#169 update
  .github/workflows/artillery-action-users-id-tasks-api.yml
Labels: bug

#168 Joanna artillery test task3 sprint3
  .github/workflows/artillery-action-users-id-tasks-id-api.yml
  testing/artillery/artillery-test-users-id-tasks-id-api.yml
Labels: task, team3

#171 renamed blob storage
  .github/workflows/artillery-action-users-id-tasks-id-api.yml
Labels: bug, team3

#173 updating artillery Report
  .github/workflows/artillery-action-users-id-tasks-api.yml
Labels: bug, task, team3

#174 Juno-Artillery test for /users/{user_id}-10 concurrent requests per second for 5 mins
  .github/workflows/artillery-action-users-userid-api.yml
  testing/artillery/artillery-test-users-userid-10con-5min.yml
Labels: task, team3

#188 Github Action Script and Test
  .github/workflows/serverless-artillery-action-users-api.yml
  testing/Serverless-Artillery/serverless-artillery-test-users-api.yml
Labels: task, team4

#195 update workflow
  .github/workflows/artillery-action-users-id-tasks-id-api.yml
  testing/artillery/artillery-test-users-id-tasks-id-api.yml
Labels: bug, team3

#193 Sprint3][Team3][Task5]-Serverless Artillery test for /users/{user_id}/tasks-10 concurrent requests per second for 5 mins
  .github/workflows/serverless-art-user-userid-task.yml
  testing/Serverless-Artillery/test-users-userid-tasks.yml
  testing/results/users-userid-tasks.json
Labels: task, team3

#196 Team4 task5 pn
  prototype/prototype-redis-connection.py
  testing/artillery/report_for_30req.json.html
Labels: task, team4

#189 [Automationspn sprint3] automation to create function resources (Function app, Appservice plan, AppInsights, and Storage account)
  automation/functions/azuredeploy.json
  automation/functions/script.ps1
Labels: task, team2

#200 rename file
  .github/workflows/deploy-azure-function.yml
Labels: task, team4

#204 [TASK 5]Vita/issues/127 artillery results react
  testing/artillery/report_for_30req.json.html
  ui/package-lock.json
  ui/src/App.js
  ui/src/components/data/report_for_30req.json
  ui/src/components/pages/ArtilleryDetailScreen.js
  ui/src/components/pages/ArtilleryListScreen.js
Labels: task, team1

#185 [TEAM 2 | TASK 1 | SPRINT 3] Run the automation to create the storage account and the necessary containers in it.
  automation/functions/storage/createstorageaccount.ps1
  automation/functions/storage/template.json
Labels: task, team2

#205 Serverless /users action v2
  .github/workflows/serverless-artillery-action-users-api.yml
Labels: task, team4

#206 Small naming/typo fix
  .github/workflows/serverless-artillery-action-users-api.yml
Labels: task, team4

#207 Vita/issues/127 artillery results react
  ui/src/components/pages/ArtilleryListScreen.js
  ui/src/components/pages/ServerlessListScreen.js
Labels: bug, task, team1

#194 [Sprint3] automation to create SQL resources
  automation/functions/SQL/deployAzure.json
  automation/functions/SQL/deployAzureSQL.ps1
Labels: task, team2

#227 fixes github action to only upload built files
  .github/workflows/deploy-ui.yml
Labels: bug, team4

#144 Derek task4 sprint2 bug fix
  automation/ip-address-script/create-ip.ps1
Labels: bug, team3
