Repository North-Seattle-College/ad440-winter2021-tuesday-repo, pull requests merged in 2021-01, with the labels that each got.

#4 [Task] Task 6: Create a React UI
  ui/.gitignore
  ui/README.md
  ui/package-lock.json
  ui/package.json
  ui/public/favicon.ico
  ui/public/index.html
  ui/public/logo192.png
  ui/public/logo512.png
  ui/public/manifest.json
  ui/public/robots.txt
  ui/src/App.css
  ui/src/App.js
  ui/src/App.test.js
  ui/src/index.css
  ui/src/index.js
  ui/src/logo.svg
  ui/src/reportWebVitals.js
  ui/src/setupTests.js
Labels: task, team1

#33 Team4 sprint1 task4
  .gitignore
  testing/Serverless-Artillery/script.yml
Labels: task, team4

#34 Team04 sprint01 task03
  testing/artillery/vm_url_performance.yml
Labels: task, team4

#35 Update serverless artillery test script
  testing/Serverless-Artillery/script.yml
Labels: task, team4

#37 Implement script to create Azure functions
  automation/functions/deploy-script.ps1
  automation/functions/template.json
Labels: task, team2

#32 Write script to log in to azure portal create resource and storageaccount
  automation/functions/.gitignore
  automation/functions/create_azure_storageacct.ps1
Labels: task, team2

#46 Team04 sprint01 task06
  testing/kubernetes-perf-test/.dockerignore
  testing/kubernetes-perf-test/Dockerfile
  testing/kubernetes-perf-test/armdeploy.json
  testing/kubernetes-perf-test/package-lock.json
  testing/kubernetes-perf-test/perftest.yaml
Labels: task, team4

#45 Junom task3 create nsg script
  automation/network-security-group/create-nsg.ps1
Labels: task, team3

#41 Create Virtual Network PS Script
  automation/vnet/deploy-vnet.ps1
Labels: task, team3

#44 Derek task5
  automation/ip-address-script/create-ip.ps1
Labels: task, team3

#40 Task 4- Implement script to create Azure Function for /users/{user_id}/tasks/{task_id} API
  .DS_Store
  automation/.DS_Store
  automation/function-automation/Task4Script/azuredeploy.json
  automation/function-automation/Task4Script/deployfunctionScript.ps1
Labels: task, team2

#49 Adds DS_Store, VScode environments to gitignore
  .DS_Store
  .gitignore
  automation/.DS_Store
Labels: bug, important

#39 Tues sprint1 task4 amb
  .gitignore
  functions/.funcignore
  functions/.gitignore
  functions/GetTasks/__init__.py
  functions/GetTasks/function.json
  functions/GetTasks/sample.dat
  functions/HttpTriggerDeleteTask/__init__.py
  functions/HttpTriggerDeleteTask/function.json
  functions/HttpTriggerDeleteTask/sample.dat
  functions/HttpTriggerGetTask/__init__.py
  functions/HttpTriggerGetTask/function.json
  functions/HttpTriggerGetTask/sample.dat
  functions/HttpTriggerPutTask/__init__.py
  functions/HttpTriggerPutTask/function.json
  functions/HttpTriggerPutTask/sample.dat
  functions/Model/Task.py
  functions/Model/User.py
  functions/Utils/ExceptionWithStatusCode.py
  functions/Utils/RequestHandler.py
  functions/Utils/dbHandler.py
  functions/host.json
  functions/proxies.json
  functions/requirements.txt
Labels: bug, task, team1

#48 Team1-Sprint1-Task1-bso
  .gitignore
Labels: task, team1

#29 Automationspn
  .DS_Store
  automation/.DS_Store
  automation/functions/azuredeploy.json
  automation/functions/script.ps1
Labels: task, team2

#47 Jg task4
  automation/vm/deploy-vm.ps1
  automation/vm/parameters.json
  automation/vm/template.json
Labels: team3

#36 pk sprint1 task2
  .funcignore
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  functions/CreateUserId/__init__.py
  functions/CreateUserId/function.json
  functions/CreateUserId/sample.dat
  functions/DeleteUserId/__init__.py
  functions/DeleteUserId/function.json
  functions/DeleteUserId/sample.dat
  functions/GetUserId/__init__.py
  functions/GetUserId/function.json
  functions/GetUserId/sample.dat
  functions/Model/Task.py
  functions/Model/User.py
  functions/Utils/ExceptionWithStatusCode.py
  functions/Utils/RequestHandler.py
  functions/Utils/dbHandler.py
  functions/local.settings.json
  functions/requirements.txt
  host.json
  local.settings.json
  proxies.json
  requirements.txt
Labels: bug, task, team1

#56 Deleted vscode folder
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
Labels: bug

#60 New UI
  .gitignore
  ui/package-lock.json
  ui/package.json
  ui/public/index.html
  ui/public/nsc.ico
  ui/src/App.js
  ui/src/components/css/App.css
  ui/src/components/css/Button.css
  ui/src/components/css/HomeScreen.css
  ui/src/components/css/Index.css
  ui/src/components/css/NavLinks.css
  ui/src/components/css/NavScreen.css
  ui/src/components/css/TaskScreen.css
  ui/src/components/css/TasksDetailsScreen.css
  ui/src/components/css/UsersScreen.css
  ui/src/components/data/dummy-tasks.json
  ui/src/components/data/dummy-users.json
  ui/src/components/hooks/axios-hook.js
  ui/src/components/navigation/NavLinks.js
  ui/src/components/navigation/NavScreen.js
  ui/src/components/pages/HomeScreen.js
  ui/src/components/pages/TaskDetailsScreen.js
  ui/src/components/pages/TasksScreen.js
  ui/src/components/pages/UsersScreen.js
  ui/src/components/uiElements/Button.js
  ui/src/index.js
Labels: team1

#78 Updated arm template and script
  automation/functions/azuredeploy.json
  automation/functions/script.ps1
Labels: task, team2

#82 Git action to deploy function to azure
  .github/workflows/deploy-Az-function.yml
Labels: task, team4

#84 Sprint 2] team 4] task 6 change the yaml for artillery on the vm to test the /users api with 100 req/sec for 15 mins
  testing/artillery/perf_test_userapi.yaml
Labels: task, team4
